{"name": "Create order with invalid ingredient hash", "status": "passed", "description": "This test verifies that an order creation attempt with an invalid ingredient hash returns a 500 Internal Server Error.", "start": 1723391614534, "stop": 1723391614740, "uuid": "d804d6e7-2d4e-4f0f-88d7-b353eda79b54", "historyId": "70b892f8b0761e734d89f7532bbf49e8", "testCaseId": "70b892f8b0761e734d89f7532bbf49e8", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_with_invalid_ingredient_hash", "labels": [{"name": "suite", "value": "Order Creation Tests"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "DESKTOP-OODMP73"}, {"name": "thread", "value": "15196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}