{"name": "Create order with invalid ingredient hash", "status": "failed", "statusDetails": {"message": "AssertionError: User creation failed\nassert False", "trace": "@pytest.fixture\n    def create_user():\n        payload = User.register_new_user()\n    \n        requests.delete(config.DELETE_USER_PATH, json=payload)\n    \n        response = requests.post(config.CREATE_USER_PATH, json=payload)\n    \n        if response.status_code != 200:\n            print(f\"User creation failed with status code {response.status_code}\")\n            print(f\"Response body: {response.json()}\")\n>           assert False, \"User creation failed\"\nE           AssertionError: User creation failed\nE           assert False\n\ntests\\conftest.py:23: AssertionError"}, "description": "This test verifies that an order creation attempt with an invalid ingredient hash returns a 500 Internal Server Error.", "attachments": [{"name": "stdout", "source": "4103618d-0140-4a93-947d-c40fbf061a8a-attachment.txt", "type": "text/plain"}], "start": 1723391592887, "stop": 1723391592887, "uuid": "0aece252-f0cc-417a-9fdb-78f3d114d7e8", "historyId": "70b892f8b0761e734d89f7532bbf49e8", "testCaseId": "70b892f8b0761e734d89f7532bbf49e8", "fullName": "tests.test_create_order.TestCreateOrder#test_create_order_with_invalid_ingredient_hash", "labels": [{"name": "suite", "value": "Order Creation Tests"}, {"name": "parentSuite", "value": "tests"}, {"name": "subSuite", "value": "TestCreateOrder"}, {"name": "host", "value": "DESKTOP-OODMP73"}, {"name": "thread", "value": "6128-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_create_order"}]}